//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringTourSystem.Infrastructure.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class location_tour_guide
    {
        public int tour_guide_id { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
    }
}
