# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TourGuide' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Typhoon'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', '~> 3.0'
  pod 'MBProgressHUD', '~> 0.9'
  pod 'SDWebImage'
  pod 'GoogleMaps'

  # Pods for TourGuide

  target 'TourGuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TourGuideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
